/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Advertisements {
  created_date: Generated<Timestamp>;
  created_user: Generated<string>;
  end_date: Timestamp;
  id: Generated<number>;
  image_name: string;
  image_type: string;
  link_type_id: number | null;
  linked_id: number | null;
  name: string;
  priority_id: number;
  start_date: Timestamp;
  summary: string | null;
  updated_date: Timestamp | null;
  updated_user: string | null;
}

export interface Emails {
  email: string;
  id: Generated<number>;
  message: string;
  name: string;
}

export interface Events {
  description: string | null;
  end_date: Timestamp | null;
  event_type_id: number;
  id: Generated<number>;
  image_name: string | null;
  image_type: string | null;
  name: string | null;
  reoccurence_type_id: number | null;
  start_date: Timestamp | null;
  status_type_id: Generated<number>;
  thumbnail_name: string | null;
  thumbnail_type: string | null;
}

export interface EventTypes {
  id: Generated<number>;
  name: string | null;
}

export interface LinkTypes {
  id: number;
  name: string | null;
}

export interface Posts {
  createdDate: Timestamp | null;
  fbId: string | null;
  id: Generated<number>;
  message: string | null;
}

export interface PriorityTypes {
  id: number;
  name: string | null;
}

export interface ReoccurenceTypes {
  id: Generated<number>;
  name: string | null;
}

export interface StatusTypes {
  id: Generated<number>;
  name: string | null;
}

export interface DB {
  advertisements: Advertisements;
  emails: Emails;
  event_types: EventTypes;
  events: Events;
  link_types: LinkTypes;
  posts: Posts;
  priority_types: PriorityTypes;
  reoccurence_types: ReoccurenceTypes;
  status_types: StatusTypes;
}
